<?php
/* @var \Vnext\TrainingModule\Block\Template $block */
?>
<?php $gridrecords = $block->GetSutudentById(); ?>
<div style="color: red;border: 1px solid #00ade2;padding-left: 20px;padding-top: 20px;
">
    <p>Tên học sinh : <?php echo $gridrecords->getName() ?></p>
    <br>
    <p>Giới tính : <?php echo $gridrecords->getGender() ?></p>
    <br>
    <p>Địa chỉ : <?php echo $gridrecords->getaddress() ?></p>
    <br>
    <p>Ngày sinh : <?php echo date('d-m-Y', strtotime($gridrecords->getDob())) ?></p>
</div>
