<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>
<?php $gridrecords = $block->getCustomCollection(); ?>
<?php if ($gridrecords && sizeof($gridrecords)): ?>

    <!-- Search form -->
    <form action="<?= $block->escapeHtml($block->getUrl('student.html')) ?>" method="post">
        <input name="name" class="form-control" type="text" placeholder="Name" aria-label="Search" width="50px">
        <br>
        <br>
        <input name="entity_id" class="form-control" type="text" placeholder="ID" aria-label="Search">
        <br>
        <br>
        <label for="pet-select">Giới tính</label>
        <select name="gender" id="pet-select">
            <option value="">--Please choose an option--</option>
            <option value="nam">Nam</option>
            <option value="nữ">Nữ</option>
        </select>
        <br>
        <br>
        <label for="pet-select">Độ tuổi</label>
        <select name="dob" id="pet-select">
            <option value="">--Please choose an option--</option>
            <option value="1">5tuổi->10tuổi</option>
            <option value="2"> > 10 tuổi</option>
        </select>
        <br>
        <br>
        <b>Sắp xếp theo</b>
        <div class="radio">
            <label><input type="radio" name="optradio" value="entity_id"    >EntityId</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="optradio" value="name">Name</label>
        </div>
        <div class="radio">
            <label><input type="radio" name="optradio" value="dob">Dob</label>
        </div>

        <br>
        <br>
        <button type="submit">search</button>
    </form>
    <div class="table-wrapper orders-history">
        <br>
        <br>
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('ID') ?></th>
                <th scope="col" class="col title"><?php echo __('Ngày Thêm') ?></th>
                <th scope="col" class="col product"><?php echo __('Tên') ?></th>
                <th scope="col" class="col amount"><?php echo __('Giới tính') ?></th>
                <th scope="col" class="col amount"><?php echo __('Địa chỉ') ?></th>
                <th scope="col" class="col amount"><?php echo __('Ngày Sinh') ?></th>
                <th scope="col" class="col amount"><?php echo __('Chi Tiết') ?></th>

            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($gridrecords as $gridrecord): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('entity_id')) ?>" class="col id">
                        <?php echo $gridrecord->getId() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Created_at')) ?>"
                        class="col title"><?php echo date('d-m-Y', strtotime($gridrecord->getCreated_at())); ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Name')) ?>" class="col product">
                        <?php echo $gridrecord->getName() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Gender')) ?>">
                        <?php echo $gridrecord->getGender() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Address')) ?>">
                        <?php echo $gridrecord->getAddress() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Dob')) ?>"
                        class="col title"><?php echo date('d-m-Y', strtotime($gridrecord->getDob())); ?></td>
                    <td><a name="idS" href="student.html/detail?idS=<?= $gridrecord->getId() ?>"><button>Chi Tiết</button></a></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
<?php endif ?>